version: '3'

services:
  mqtt:
    image: benny2/mosquitto-websocket # Usar la imagen de Mosquitto con WebSocket
    ports:
      - "1883:1883"
      - "9001:9001"
    container_name: mqtt_server

  web:
    build:
      context: ./100halconesdijeron
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: web_app
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883

  db: # Servicio de base de datos MySQL 
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: halcones
      MYSQL_USER: halcones
      MYSQL_PASSWORD: 1234567890
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
